services:
  app:
    build:
      context: .
      target: production
    ports:
      - ${HOST_PORT:-8082}:8080
    env_file:
      - .env
    environment:
      MYSQL_HOST: db
      SPRING_ENV: prod
    networks:
      - fullstack_network
    depends_on:
      db:
        condition: service_healthy
    profiles: ["manual"]

  db:
    image: mysql:lts
    ports:
      - ${HOST_DB_PORT:-3306}:3306
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fullstack_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15m
      timeout: 5s
      retries: 5
      start_period: 30s
      start_interval: 1s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT:-8088}:80
    env_file:
      - .env
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - fullstack_network
    depends_on:
      db:
        condition: service_healthy
volumes:
  mysql_data:

networks:
  fullstack_network:
    name: ${DOCKER_DOMAIN_NETWORK:-fullstack_network}
