services:
  app:
    build:
      context: .
      target: production
    ports:
      - ${HOST_PORT:-8082}:8080
    env_file:
      - .env
    environment:
      MYSQL_HOST: db
      SPRING_ENV: prod
    networks:
      - fullstack_network

networks:
  fullstack_network:
    name: ${DOCKER_DOMAIN_NETWORK:-fullstack_network}
