# App
spring.application.name=${SPRING_APP_NAME}
server.port=8080
spring.log.level=${SPRING_LOG_LEVEL:INFO}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

# Security
jwt.secret=${SPRING_JWT_SECRET}
jwt.issuer=${SPRING_JWT_ISSUER}
jwt.public=${SPRING_JWT_PUBLIC}

# OpenAPI / Swagger
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
