# App
spring.application.name=${SPRING_APP_NAME}-dev
server.port=${HOST_PORT}
spring.log.level=${SPRING_LOG_LEVEL}

# Security
jwt.secret=${SPRING_JWT_SECRET}
jwt.issuer=${SPRING_JWT_ISSUER}
jwt.public=${SPRING_JWT_PUBLIC}

# OpenAPI / Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
