# Documentation Metadata
springdoc.openapi.info.title=VetManager Microservice API
springdoc.openapi.info.version=v0.1
springdoc.openapi.info.description= This microservice acts as a gateway for \
                                    domain microservices and provide advanced \
                                    use-cases.

# Actuator
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=${springdoc.openapi.info.title}
info.app.environment=${spring.profiles.active}
