# Documentation Metadata
springdoc.openapi.info.title=VetManager Microservice API
springdoc.openapi.info.version=v0.1
springdoc.openapi.info.description= This microservice acts as a gateway for \
                                    domain microservices and provide advanced \
                                    use-cases.
